### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pthariensflame** [alissapajer/conferenceslides#1]
In the _flatMap(Oslo)_ slides, there is a typo on slide 14: the Haskell code given doesn't compile.

``` haskell
toList :: Maybe Bool -> [Bool]
toList Nothing = []
toList Just b = [b]
```

should be

``` haskell
toList :: Maybe Bool -> [Bool]
toList Nothing = []
toList (Just b) = [b]
```

**Comment by alissapajer** [comment]
Thanks! Just pushed the fix.

http://alissapajer.github.io/conferenceslides/flatmaposlo2014/#/14

**Comment by pthariensflame** [comment]
I'm not sure why this was still open!  :O
